### ISSUE TITLE
Verify that Lowe's products are on the site

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#150]
Need to verify that the PDP adjusts for the Lowe's / Non-Lowe's products

**Comment by MartyBeckers** [comment]
Yes I can confirm that the logic is correctly displaying the Lowe's/Generic blue boxes depending on the value of the product "Lowe's Exclusive" checkbox (a Lowe's product can be seen at http://dev.culligandiy.com/Undersink-Systems/Ultra-Filtration-Systems/Ultrafiltration-System-with-SureLock and a non-Lowe's product can be seen at http://dev.culligandiy.com/Undersink-Systems/Direct-Connect-Systems/Advanced-Under-Sink-Filter-System,-Easy-Change).

Verifying if the checkbox is correct for each of the products is a different matter.  For instance, I initially migrated the "Basic Under Sink Filter System" product from the previous site at http://www.culligandiy.com/Filter-Systems/Drinking-Water/Basic-Under-Sink-Filter-System-US-600A/, and the URL spreadsheet indicates it's a "Carryover Product" rather than a "Lowe's Product", so I left the "Lowe's Exclusive" checkbox unchecked.  Then recently, someone checked the Lowe's box (Kentico says Josh Berg was the last person to modify the product but it doesn't indicate who changed what).  I don't think that's correct, but we don't have a definitive list showing Lowe's/non-Lowe's products to compare to, so without that we would need the client to verify the products are correct.
