### ISSUE TITLE
Home [Tablet]: Quote is missing padding

### ISSUE THREAD

**Issue by mikewestaz** [nickpaventi/culligan-diy#87]
Should have equal padding below the text as is above it (blue)

![tablet-home-quote-missing-padding](https://cloud.githubusercontent.com/assets/10550484/7075952/a205bc58-deba-11e4-92cb-c2325f8a2604.png)

**Comment by nickpaventi** [comment]
@MartyBeckers can you add this JS (or show me where to) for the blue-banner section?

```javascript

<script type="text/javascript">
$(document).ready(function(){
    var max_h = $('.banner-content').outerHeight();
    $('.blue-banner').css('max-height', max_h+'px'); 

    $(window).resize(function(event) {
    	if ($(this).width() > 767){
	    	var max_h = $('.banner-content').outerHeight();
	    	$('.blue-banner').css('max-height', max_h+'px'); 
	    }
	    else { $('.blue-banner').css('max-height', 'none'); }
    });
});
</script>
```

**Comment by MartyBeckers** [comment]
Sure, that's in place except that the document ready piece needs to be:

jQuery(document).ready(function($) {

because of a conflict with the Kentico jQuery library.  Then within the function, the dollar sign can be used again.  And for future reference, template-specific JavaScript can be placed in http://dev.culligandiy.com/CMSSiteManager/ > Development > Page templates > Culligan DIY > [template] > Header

**Comment by nickpaventi** [comment]
Got it, thanks!
